Removing references to CockroachCloud for now.
cockroachlabs/hello-world-python-psycopg2 pull request #2
Opened 2020-11-04 21:04 UTC by ianjevans

Part of https://github.com/cockroachdb/docs/issues/7816

2020-11-04 21:17 UTC, dvarrazzo requested changes

2020-11-04 21:17 UTC, dvarrazzo commented on README.md
> +This repo has a "Hello World" Python application that uses the [`psycopg2`](https://www.psycopg.org/docs/install.html) driver to talk to either a temporary local CockroachDB cluster.
You have a spurious "either" here

2020-11-04 21:48 UTC, ericharmeling approved these changes
LGTM!

2020-11-05 00:39 UTC, dvarrazzo approved these changes

2020-11-05 01:13 UTC, merged